### ISSUE TITLE
Upgrade to more recent Django version

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#10]
Update Django to Django 4.2 in a first step and to 5.0 in a second step.

**Comment by rakesh-nj** [comment]
Hey ! I have experience in Django and DjangoRestFramework . I would like to contribute to it  . Could you please assign it to me ?

**Comment by mariobehling** [comment]
Ok, great. We do not assign issues to new contributors. Please just make a PR. You can also contribute to an existing PR here https://github.com/fossasia/eventyay-tickets/pull/34 and finish it. Thanks!
