### ISSUE TITLE
Change system branding

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#103]
* Change name to "eventyay"
* Use same logo as on eventyay-talk
* Change to "powered by eventyay" with link to eventyay.com
* Change the name "pretix" in all text fields to "the system" or similar. It should make sense.
* In Readme.md change from Pretix to Eventyay-Tickets

Compare to https://github.com/fossasia/eventyay-talk/pull/69/files

![Screenshot from 2024-05-22 18-57-10](https://github.com/fossasia/eventyay-tickets/assets/1583873/c3b54405-6a79-407a-8759-3b940a6a6c80)

**Comment by progmatic-99** [comment]
working on this

**Comment by AviGawande** [comment]
due issue #103 being closed and i had to raise the PR to the main repo

**Comment by mariobehling** [comment]
Yes, please go ahead. Reopened the issue. Please finish the remaining items. Thanks
