### ISSUE TITLE
Update Paypal Implementation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#12]

**Comment by NaviRocker** [comment]
It would be easier to work on this if you could provide some description!

**Comment by FelixFelicis555** [comment]
I'm claiming this issue,Could you assign the issue to me?

**Comment by abhay-raj19** [comment]
@mariobehling can you pls elaborate more on this issue, as I would like to work on it, pls explain it
It would be a great help for all of us to contribute!!

**Comment by vaishnavi192** [comment]
@mariobehling can you plz tell tell what all things we have to implement? I would like to work on this issue

**Comment by sahil-1729** [comment]
is the issue still open?
