### ISSUE TITLE
Perform Dependency Upgrades and System Fixes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#130]
Perform the following upgrades and maintenance

* [ ] Replace slimit with https://pypi.org/project/rjsmin/
* [ ] Upgrade jQuery
* [ ] PDF: Upgrade fabric.js
* [ ] Upgrade package-lock to v2
* [ ] Get rid of unmaintained dependency python-u2flib-server
* [ ] Upgrade NodeJS
* [ ] Improve npm install call in pyproject.toml (previously setup.py)
* [ ] Update webauthn requirement from to ==2.0
* [ ] Update django-oauth-toolkit requirement to ==2.3.
* [ ] Upgrade celery to 5.4.*
* [ ] chardet to 5.2.*
* [ ] css-inline to 0.14.*
* [ ] django-bootstrap3 to 24.2
* [ ] django-compressor to 4.5
* [ ] django-countries to 7.6.*
* [ ] django-filter to 24.2
* [ ] django-formtools to 2.5.1
* [ ] django-hierarkey to 1.2.*
* [ ] django-hijack 3.5.*
* [ ] django-otp	1.5.*
* [ ] django-phonenumber-field	7.3.*
* [ ] django-statici18n	2.5.*
* [ ] djangorestframework	3.15.*
* [ ] importlib_metadata	8.*
* [ ] libsass	0.23.*
* [ ] markdown	3.6
* [ ] Pillow	10.3.*
* [ ] protobuf	5.27.*
* [ ] pycparser	2.22
* [ ] python-dateutil	2.9.*
* [ ] reportlab	4.2.*
* [ ] stripe	7.9.*
* [ ] tqdm	4.66.*
* [ ] webauthn	2.2.*
* [ ] fakeredis	2.23.*
* [ ] flake8	7.1.*
* [ ] isort	5.13.*
* [ ] pep8-naming	0.14.*
* [ ] pytest	8.2.*
* [ ] pytest-mock	3.14.*
* [ ] pytest-rerunfailures	14.*
* [ ] pytest-xdist	3.6.*
* [x] Keep dependencies in one place
* [x] Upgrade mt-940
* [x] Upgrade django-phonenumber-field
* [x] PDF: replace deprecated PdfMerger with PdfWriter
* [x] PDF: Upgrade PyPDF

**Comment by eMBee** [comment]
from this list:

the npm install call has been moved to pyproject.toml. i don't know if it needs more work.

other entries without a version have been upgraded, but not necessarily to the latest version.  further upgrades may be desired.

**Comment by hongquan** [comment]
I saw `slimit` as one of dependencies. Don't know where it is used. It is too old (last released in 2013). If it is used, we may replace with https://pypi.org/project/rjsmin/.

**Comment by AviGawande** [comment]
yes @hongquan the slimit is obsolete and no longer maintained,it is used for the javascript minification,we can upgrade to "rjsmin 1.2.2"
