### ISSUE TITLE
Add options for Single Sign On

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#131]
In order to enable Single Sign On (SSO) we need signals that are currently not dispatched when a user signs in or creates an account.

The goal is to allow something like this to be implemented as a plugin.

There is no concept of plugins being enabled and disabled on organizer level currently, so a plugin needs to take care of that itself through settings.

**Comment by odkhang** [comment]
Hi @mariobehling , so basically this issue we just need dispatch the signals whenever user login or create new account? is it correct?

**Comment by mariobehling** [comment]
@odkhang Basically, we need SSO to work together with eventyay-talk and eventyay-tickets. So, whatever is missing to get it working is needed in this PR. You need to install the three components on your system and test that they work together.

I should have previously clarified that we also need you to show that this works on the online installed components, please. You can show the outcome on the online system at the weekly meeting.

**Comment by mariobehling** [comment]
Implemented in https://github.com/fossasia/eventyay-tickets/pull/223
