### ISSUE TITLE
Deactivate Perform update checks by default

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#137]
"Perform update checks" is activated by default. Please deactivate it by default.

https://tickets-dev.eventyay.com/control/global/update/

![Screenshot from 2024-06-10 20-28-04](https://github.com/fossasia/eventyay-tickets/assets/1583873/011390e8-3212-41f9-bd03-c6d6f2463283)

**Comment by AviGawande** [comment]
hey Mario,raised the PR  #162 fixes this issue and closes it
