### ISSUE TITLE
Update Stripe to more recent version

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#150]
The Stripe implementation is outdated. Update the implementation to a more recent version.

**Comment by mariobehling** [comment]
While this implementation works functionally, it is not as needed in regards to different users.

Previously the component was implemented in a way that separates functionality of eventyay admins and event organizer users. With the last PR the implementation is that all functionality is in the event organizer (user) space.

1. Keep the functionality for admins in /control/global/settings/
![Screenshot from 2024-06-20 13-45-53](https://github.com/fossasia/eventyay-tickets/assets/1583873/defc0e1e-7810-4834-b5ff-105430022a2b)

2. Keep the functionality for users in the payment area of the component similar to the current Pretix and open-event.
![Screenshot from 2024-06-20 13-47-36](https://github.com/fossasia/eventyay-tickets/assets/1583873/2fad0ae1-b0b5-4d59-befc-00bdb54789b6)

**Comment by mariobehling** [comment]
We also need to test what is the "transfer key" sent with the transaction. It should be the event name that shows up in Stripe as a transfer info.

**Comment by lcduong** [comment]
Hi @mariobehling,

1. the global setting is the same as previous, for admin to config the stripe key
![image](https://github.com/fossasia/eventyay-tickets/assets/51145179/e943a9ad-3c3e-4ef2-8922-e8cc3959055a)

2. in user area also the same as previous. incase admin net setup key in global config, user need to setup as theirself.

![image](https://github.com/fossasia/eventyay-tickets/assets/51145179/3bf11080-2993-4d2f-a469-15f0d12e067e)
