### ISSUE TITLE
Do not repeat questions in form field of ticket form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#215]
Currently questions are repeated in form fields. This is not required and even confusing. Change the implementation to not show questions in the form fields.

![Screenshot from 2024-06-26 13-39-41](https://github.com/fossasia/eventyay-tickets/assets/1583873/ef6cb11b-1ff1-4e8d-9f6d-b6f5018694ec)

**Comment by AviGawande** [comment]
having problem to create this issue on my local development setup,is this path correct for = /control/event/<organizer>/<event_slug>/questions/

**Comment by mariobehling** [comment]
You can test it here: https://tickets-dev.eventyay.com/eteam/wikimania-test/

**Comment by AviGawande** [comment]
sure

**Comment by odkhang** [comment]
Hi @mariobehling,
do you want to have other placeholder or we completely remove it?
and which type should we remove repeat placeholder? currently 'text one line', 'text multiple line' and phone number have the same placeholder with it label.

**Comment by mariobehling** [comment]
@odkhang Good question. Basically we should follow Google forms.

In the fields just show "Your answer"
In the email fields show "Valid Email address"
In the phone number field show "Phone"
