### ISSUE TITLE
Add Eventyay-Talk component to User-Dashboard

### ISSUE THREAD

**Issue by AviGawande** [fossasia/eventyay-tickets#257]
This is the feature that will provide the user to connect the eventyay-talk with eventyay-tickets by enabling to access both the components through one dashboard.

**Comment by mariobehling** [comment]
Closing this as solved through different PRs including [PR #310](https://github.com/fossasia/eventyay-tickets/pull/310) and [PR #350](https://github.com/fossasia/eventyay-tickets/pull/350).
