### ISSUE TITLE
Add translation for placeholder "Join online event"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#279]
In emails the placeholder "Join online event" is not translated to other languages. Add the translation for Russian, Ukrainian, Arabic, Spanish and French

**Comment by odkhang** [comment]
Hi @mariobehling,

the {join_online_event} currently return: 

` <a href="https://wikimania-live.eventyay.com/xxxxxxxxx" class="button">Join online event</a>`

'Join online event' is hard code, and cannot detect receiver's language to translate

So for translate it in mail, for {join_online_event}, I will return only url "https://wikimania-live.eventyay.com/xxxxxxxxx"

Then in your mail setting, you can set the language for it like below screenshot, is it okay?

![image](https://github.com/user-attachments/assets/2ea77f67-2776-4884-8aff-51cd4364ba8c)

![image](https://github.com/user-attachments/assets/ce27d4f5-e442-4380-8c8b-a954910412f2)

PR: https://github.com/fossasia/eventyay-tickets/pull/284
