### ISSUE TITLE
Add PostgreSQL and Redis TLS/mTLS support

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#28]
The original version of Pretix has implemented support for PostgreSQL in this PR https://github.com/pretix/pretix/pull/3435/files

Please implement the support here as well.

**Comment by Shivangi-ch** [comment]
I have started working on this issue and will make a Pull request soon.

**Comment by angel-dot-exe** [comment]
@mariobehling I have attempted to resolve the issue, please review the PR.

**Comment by hongquan** [comment]
Where is your PR, @fillingtothemomo ?

**Comment by angel-dot-exe** [comment]
@hongquan I made a PR few days ago it's linked to this issue, https://github.com/fossasia/eventyay-tickets/pull/45

**Comment by hongquan** [comment]
Someone who plan to work on this issue, please remember that you are not allowed to copy code from https://github.com/pretix/pretix/ which are younger than this commit [ce834d7](https://github.com/pretix/pretix/commits/ce834d7028d12711b5ddde729908ee7ce83024a9/).
