### ISSUE TITLE
Provide option to deactivate the sale of a ticket without an account

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#282]
There are currently three options when buying a ticket
a) create an account
b) use an existing account
c) buy as a guest

Expected: The organiser should have the option to require customer accounts for ticket types.

**Comment by Yadavanurag13** [comment]
Can we do it like deactivate the sales from admin panel?

**Comment by Arpitalite** [comment]
I’d like to work on this issue. Is it still available?
