### ISSUE TITLE
Change config and system name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#30]
Change the config and system names to eventyay.

**Comment by NaviRocker** [comment]
Recommended for beginners who are new to open-source contributions! Anyone?

**Comment by NaviRocker** [comment]
Taking It Since No one is there!

**Comment by weshaan** [comment]
still on?

**Comment by sergyDwhiz** [comment]
I don't think he Submitted a PR. So I'm on it

**Comment by angel-dot-exe** [comment]
@NaviRocker  @mariobehling I would like to take this issue up, please assist me as to what is to be done.

**Comment by mariobehling** [comment]
Go ahead. There is no need to announce you are taking it up. Just go ahead and make a PR.
