### ISSUE TITLE
Update color theme 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#31]
Change color codes to eventyay

Colors, Change:
1. purple to eventyay blue - #2185d0

2. All semi transparent green area to light grey (Please propose a suitable grey color)

3. All cancel/discard button to red; #db2828

4. Save button to blue: #2185d0

5. Frontpage header colors default: #2185d0

compare https://github.com/fossasia/eventyay-talk/issues/7

**Comment by NaviRocker** [comment]
Hi @mariobehling, I am claiming this Issue!

**Comment by sergyDwhiz** [comment]
On it...

**Comment by sergyDwhiz** [comment]
Hey @mariobehling, I have difficulty navigating to the directory where this issue should be solved! 
Thank you!

**Comment by Shivangi-ch** [comment]
@Sergius-Nyah there is already a PR - #41 for this issue. If you want you can review the PR and leave your review comments if you have any.
