### ISSUE TITLE
Change default settings for background color, invoice attachments and name scheme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#32]
Change default settings for background color, invoice attachmentes and name scheme.

The goal of this PR to introduce straight forward changes similar to the PR in the original Pretix project here https://github.com/pretix/pretix/pull/2288/files

**Comment by DaSeeker67** [comment]
hello @hpdang  @mariobehling  please assign this to me

**Comment by mariobehling** [comment]
@DaSeeker67 Thank you for your interest. Issues are not usually assigned to new contributors. If you would like to solve this issue you can simply create a PR. It is unlikely that someone else would solve issues in the meantime.

**Comment by himanshugupta11002** [comment]
@mariobehling   @hpdang , I have submitted a pull request for this issue. Could you please review it and provide some feedback on the changes I've made?

**Comment by weshaan** [comment]
still open?
