### ISSUE TITLE
Bump project to Python 3.11

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#33]
Update the project to Python 3.11. Similar changes were done in Pretix here https://github.com/pretix/pretix/pull/2982/files

**Comment by weshaan** [comment]
still on? i can do this

**Comment by mariobehling** [comment]
Go ahead. No need to wait for anyone. Can just make a PR.

**Comment by hongquan** [comment]
There is another PR https://github.com/fossasia/eventyay-tickets/pull/36

But I marked it as WIP because we haven't tested `eventyay-tickets` with Python 3.10+ yet. With many 6 year old dependencies, I doubt they work with Python 3.10.

**Comment by hongquan** [comment]
In the meantime, someone please remove Python 3.6, 3.7 from GitHub Action script. GitHub seems no longer provide runners with these Python versions.

**Comment by Shivangi-ch** [comment]
> In the meantime, someone please remove Python 3.6, 3.7 from GitHub Action script. GitHub seems no longer provide runners with these Python versions.

@hongquan I have fixed this issue in PR #51
