### ISSUE TITLE
Organiser profile billing settings option missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#380]
The organiser profile should be available from the organiser menu at "Billing Settings" at slug /profile, e.g. https://app-test.eventyay.com/tickets/control/event/conferenceorganiser/profile/

This URL currently shows an internal server error. If the feature is not available please implement it. Same applies to billing details. It shows internal error, e.g. https://app-test.eventyay.com/tickets/control/event/conferenceorganiser/billing/

Instead of implementing the feature in the tickets component, implement it in **eventyay-common**.

![Screenshot from 2024-10-09 19-12-20](https://github.com/user-attachments/assets/df735079-0c27-48f1-8723-b006566b5c36)

![Screenshot from 2024-10-09 19-24-48](https://github.com/user-attachments/assets/50623b63-7820-4a5a-ae60-7fd736fc1e13)

**Comment by odkhang** [comment]
Hi @mariobehling,
this feature is not implemented yet in eventyay-tickets, please add more detail what information will be showed in Settings - Billing  settings, Billing - Billing, Billing - One-off fess? please give as much info about what will be showed as possible, then we can implement it.

**Comment by mariobehling** [comment]
Ok, understand. Then the best is if this feature gets implemented in eventyay-common.

Please follow the same approach as on eventyay-tickets (but dont implement the dropdown expansion). Keep it simple.

![Screenshot from 2024-10-10 14-04-50](https://github.com/user-attachments/assets/7e040ce6-d4dd-4115-93b7-4f8646fdd71a)

1. Make "Settings" expandable and show "Billing" below the Settings menu item.
2. Use the following text for the form boxes

---

**Primary Contact Name**  
Please provide your name or the name of the person responsible for this account in your organization.

**Primary Contact Email**  
We will use this email address for all communication related to your contract and billing, as well as for important updates about your account and our services.

**Company or Organization Name**  
Enter your organization’s legal name.

**Address Line 1**  
Street address or P.O. box.

**Address Line 2**  
Apartment, suite, unit, etc. (optional).

**ZIP Code**  
Enter your postal code.

**City**  
Enter your city.

**Country**  
Select your country.

**Tax ID (e.g., VAT, GST)**  
If you are located in the EU, please provide your VAT ID. Without this, we will need to charge VAT on our services and will not be able to issue reverse charge invoices.

**Preferred Language for Correspondence**  
Select your preferred language for all communication.

**Payment Information**  
Please enter your credit card details for monthly fee payments.

**Comment by mariobehling** [comment]
For credit card information we can use Stripe (https://docs.stripe.com/terminal/features/saving-cards/overview). Best would be to enable the organiser to save several credit cards and choose a default payment method.
