### ISSUE TITLE
Implement set pricing options and plans by admin

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#381]
**eventyay-common:** The system currently does not have a pricing structure for the event, e.g. 2.5% for tickets sold. Discuss the pricing structure with the team and implement it. Provide options for admins to set the pricing.

Also create a page at the slug /pricing with the pricing information.

**Comment by odkhang** [comment]
Hi @mariobehling, is this issue relate to fee per ticket sold of this issue fossasia/eventyay-business#82 
So we will have a setting on global settings to fee for all event? 
and about /pricing page, is it FAQ of this issue fossasia/eventyay-business#82 ?

**Comment by mariobehling** [comment]
> Hi @mariobehling, is this issue relate to fee per ticket sold of this issue fossasia/eventyay-business#82 So we will have a setting on global settings to fee for all event? and about /pricing page, is it FAQ of this issue fossasia/eventyay-business#82 ?

Correct.
