### ISSUE TITLE
Add links to specific event components

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#391]
1. On eventyay-common add an internal menu with four items linking to the specific event areas for each component: Home (Current page), Tickets, Talk, Video

![Screenshot from 2024-10-10 19-45-20](https://github.com/user-attachments/assets/2dff66f5-bd64-48d2-867d-6268b64a2de4)

2. On **all event tickets pages** add an internal menu with the same four items. Highlight the current component in blue.

![Screenshot from 2024-10-10 19-18-18](https://github.com/user-attachments/assets/af1566b3-aaf9-4772-a4ce-1b5aeecff191)

**Comment by odkhang** [comment]
Hi @mariobehling, could you please confirm "specific event areas" is control area of organizer or user area (tickets shop / schedule calendar)?

**Comment by mariobehling** [comment]
1. On eventyay-common the link to the tickets page does not work yet, e.g. https://app-test.eventyay.com/tickets/common/event/conferenceorganiser/badgetest/settings/

2. On eventyay-tickets
a) the "Home" button is missing
b) in the test events on eventyay-tickets the talk component shows a 404
c) If "Video" or "Talk" are not enabled do not show those links

**Comment by lcduong** [comment]
> 1. On eventyay-common the link to the tickets page does not work yet, e.g. https://app-test.eventyay.com/tickets/common/event/conferenceorganiser/badgetest/settings/
> 2. On eventyay-tickets
>    a) the "Home" button is missing
>    b) in the test events on eventyay-tickets the talk component shows a 404
>    c) If "Video" or "Talk" are not enabled do not show those links

hi @mariobehling,
I created pull request https://github.com/fossasia/eventyay-tickets/pull/445 for point 2

for point 1, I did checked and see it is an existing bug, when we set presale start/end for event, then in general settings, we remove presale start/end, then reload the settings page, it will cause eternal loading and running out of memory, I will open an issue for this bug.

**Comment by odkhang** [comment]
https://github.com/fossasia/eventyay-tickets/issues/446 is created for point 1

**Comment by mariobehling** [comment]
The links are not set to the right place yet, e.g. check
https://app-test.eventyay.com/tickets/control/event/tma-team/q7cft/
The menu links to the talk settings instead of the talk dashboard: https://app-test.eventyay.com/talk/orga/event/q7cft/
