### ISSUE TITLE
Eventyay-Common: Create Dropdown menu similar to the "Tickets" component

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#442]
1. Create a dropdown menue as follows:

- Dashboard
  -   Tickets
  -   Talks
  -   Video
- My Events
- Organizers
- Account
- Admin
- Logout

Change the left sidebar as follows:
* Rename "Events" to "My Events"
* Add "Accounts"

**Comment by odkhang** [comment]
Hi @mariobehling, please help me to confirm the following items:

- Dashboard

  - Tickets -> https://app-test.eventyay.com/tickets/control/
  - Talks -> https://app-test.eventyay.com/talk/orga/event/
  - Video: Currently we do not have Dashboard page for Video component, so where should we redirect to? How about redirect to https://app-test.eventyay.com:8443/control/worlds/ ?

- My Events -> https://app-test.eventyay.com/tickets/common/events/
- Organizers -> https://app-test.eventyay.com/tickets/common/organizers/
- Account -> New Account page https://app-test.eventyay.com/tickets/common/account/
- Admin -> https://app-test.eventyay.com/tickets/control/admin/
- Logout

Add new Accounts page: what is this page? this is All users of system or just User profile like https://app-test.eventyay.com/tickets/control/settings/

**Comment by mariobehling** [comment]
Yes, leave the video out for now and ensure "Admin" only shows up for actual admins, please.
