### ISSUE TITLE
Implement a dedicated plugin for SSO functionalities

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#454]
Implement the SSO functionality in a dedicated plugin and support 
a) SSO with eventyay-talk and video
b) additional providers including:
* Wikipedia/Wikimedia SSO https://www.mediawiki.org/wiki/OAuth/For_Developers
* Google
* Github

Add a section in the admin dashboard
![Screenshot from 2024-11-23 15-17-10](https://github.com/user-attachments/assets/78de4f26-6fda-4e9f-8faf-8ca35f227d98)

**Comment by odkhang** [comment]
Hi @mariobehling,
Please confirm the following points:
1. SSO with eventyay-talk and video
    - eventyay-tickets will act as SSO provider, using by eventyay-talk for login
    - video: video using jwt from URL for authentication, the JWT being generated by eventyay-tickets, so video need to be access via eventyay-ticket.

2. Wikipedia/Wikimedia + Google + Github:
    - In the login page of eventyay-tickets, we will add 3 options.
        + Login with Wikipedia/Wikimedia.
        + Login with Google
        + Login with Github
    => eventyay-tickets will be SSO client in this case. When User logged in with above services, we will create new User in eventyay-tickets (incase not created before).

**Comment by mariobehling** [comment]
Yes, correct. The above should work on an admin level. Is it possible to implement the above as a plugin instead of built-in feature?

**Comment by mariobehling** [comment]
It seems that these plugins could be suitable
* https://pypi.python.org/pypi/django-rest-framework-social-oauth2
* https://django-allauth.readthedocs.io/en/latest/

Related https://gagamil.medium.com/react-native-expo-django-facebook-authentication-sign-in-83625c49da7

**Comment by HungNguyen-tma** [comment]
Hey @mariobehling, "plugin" means something like Paypal plugin like we did, when we don't want to use or don't need it we can simply turn it off. Or we could implement it anywhere in the system? I'm having a little confusion here.

Update: I just go through the code base, maybe we could build it as a plugin, I am testing it with google first.

**Comment by mariobehling** [comment]
Hello @HungNgien Yes, correct. We already have some SSO functionality. The goal would be to move this functionality to an external plugin like Paypal and add the missing SSO functionalities. This would enable us to split responsibilities more easily and keep the system more flexible. Thanks
